import {
  AppEvent,
  FootTrafficLift,
  BrandSurveyQuestions,
  SmsResponse,
  SocialLift,
  WebLift,
} from '../components/PerformanceCards';
import {
  ClockIcon,
  EyeIcon,
  StatsIcon,
  SmartphoneIcon,
  ShopIcon,
  SurveyIcon,
  QrcIcon,
  TweetIcon,
} from '../components/Icons';

const PERFORMANCE_CARD_DATA = [
  {
    key: 'ad_play_time',
    id: 'recDkBVA72guWhohp',
    title: 'Ad Playtime Hours',
    value: 0,
    unit: 'Hours',
    row: 0,
    icon: ClockIcon,
  },
  {
    key: 'impressions',
    id: 'recFz62CPzUKfoRvn',
    title: 'Estimated Impressions',
    value: 0,
    unit: 'Impressions',
    row: 0,
    icon: EyeIcon,
  },
  {
    key: 'website_lift',
    id: 'recOZ9bdCmN9u6nXJ',
    title: 'Website Traffic & Conversion Lift',
    value: 0,
    unit: 'percentage',
    row: 1,
    requiresSetup: true,
    SetupComponent: WebLift,
    icon: StatsIcon,
  },
  {
    key: 'app_lift',
    id: 'recU5n8OAQqs2FJnL',
    title: 'App Install and App Event Lift',
    value: 0,
    unit: 'percentage',
    row: 1,
    requiresSetup: true,
    SetupComponent: AppEvent,
    icon: SmartphoneIcon,
  },
  {
    key: 'footfall_lift',
    id: 'rec2aKSrMVJM1rk2P',
    title: 'Footfall Traffic Lift',
    value: 0,
    unit: 'percentage',
    row: 1,
    requiresSetup: true,
    SetupComponent: FootTrafficLift,
    icon: ShopIcon,
  },
  {
    key: 'brand_survey',
    id: 'reclipGZQWxkm6SXR',
    title: 'Brand Survey Responses',
    value: 0,
    unit: 'percentage',
    row: 1,
    requiresSetup: true,
    SetupComponent: BrandSurveyQuestions,
    icon: SurveyIcon,
  },
  {
    key: 'sms_tracking',
    id: 'recz3geoFof1fiQpk',
    title: 'Direct Response - SMS',
    value: 0,
    unit: 'Conversions',
    row: 2,
    requiresSetup: true,
    SetupComponent: SmsResponse,
    icon: QrcIcon,
  },
  {
    key: 'social_lift',
    id: 'recicoCRIA2pRyJr3',
    title: 'Social Lift',
    value: 0,
    unit: 'Twitter Mentions',
    row: 2,
    requiresSetup: true,
    SetupComponent: SocialLift,
    icon: TweetIcon,
  },
];

export const DEFAULT_PERFORMACE_MODULES = [
  'recDkBVA72guWhohp',
  'recFz62CPzUKfoRvn',
];

export default PERFORMANCE_CARD_DATA;
